### ISSUE TITLE
Syntax Error in "website" Files

### ISSUE THREAD

**Issue by leonardo0014** [dmarc-viewer/dmarc-viewer#21]
Hi

I have just tried to start your program on a SuSE system and have seen the following syntax error. Since I am not very familiar with GIT, I am writing this here.

Here is missing an "s":
**website/choices.py line 3**
`    choice.py`

a "from website" is missing in front of it
**website/models.py line 50**
`import choices`

**website/urls.py line 22**
`import` views

Otherwise I am currently fighting with the WSGI. So something can still be added ;-)

**Comment by lukpueh** [comment]
Hi and thanks for your interest!
> 
> Here is missing an "s":
> **website/choices.py line 3**
> ` choice.py`

Fixed in 64572b8

> 
> a "from website" is missing in front of it
> **website/models.py line 50**
> `import choices`
> **website/urls.py line 22**
> `import` views

These imports shouldn't be a problem. Did Python notify you about a syntax error?

> Otherwise I am currently fighting with the WSGI. So something can still be added ;-)

Good luck. ;) Feel free to suggest enhancements for the [deployment instructions](https://github.com/dmarc-viewer/dmarc-viewer/blob/master/DEPLOYMENT.md).
